NitrateRPC plugin for Jenkins
=============================
Adam Saleh <asaleh at redhat dot com>, Jan Rusnacko <jrusnack at redhat dot com>
v1.0, 2012-06

This plugin allows easy upload of test results to Nitrate TCMS 
(http://fedoraproject.org/wiki/Nitrate). After initial configuration, after each 
build new action appears, from where you can review, change and upload results 
directly to TCMS server. Results are parsed from TestNG xml files. 

Installation
------------
* Plugin is currently not in Jenkins repo, so manual instalation is required, you may find prebuilt .hpi file in Downloads section on github (https://github.com/AdamSaleh/NitrateRPC/downloads).
* Plugin currently supports only connection to kerberized Nitrate.
* If your nitrate instance has self-signed certificate, you first need to add it to java-keystore:
**  sudo keytool -import -alias tcms -file SELFSIGNED_CERT.crt -keystore /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre/lib/security/cacerts


Features
--------
* Supports both freestyle and multiconfiguration projects
* Jenkins`s build variables (and build axes in multiconf project) are mapped to 
  environment variables in TCMS - user can create custom mapping (deselect some, 
  rename)
* Supports Kerberos authentication

Release notes
-------------

=== v1.0
Initial release

Licensing
---------
This plugin is released under GNU General Public License v.2 (see COPYING).


For developers
--------------
Communication between Jenkins (Java) and Nitrate`s XMLRPC is handled by external
TcmsRpcLibrary (hosted at https://github.com/AdamSaleh/TcmsRpcLibrary), which is 
dependency for this plugin. For building use Maven >3, older versions may have 
problems with downloading dependencies from Jenkins repository.
